name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Asegúrate de usar la versión de Node.js que requiera tu proyecto

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --prod # Asegúrate de que este comando esté configurado correctamente según tu proyecto

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_STONE_0192A050F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integraciones de GitHub (i.e. comentarios de PR)
          action: "upload"
          ###### Configuración del Repositorio/Build - Estos valores se pueden configurar para que coincidan con los requisitos de tu aplicación. ######
          # Para más información sobre la configuración del flujo de trabajo de Static Web App, visita: https://aka.ms/swaworkflowconfig
          app_location: "/" # Ruta del código fuente de la aplicación
          api_location: "" # Ruta del código fuente del API - opcional
          output_location: "dist/delivery-now-front" # Directorio de contenido de la aplicación construida - opcional
          ###### Fin de Configuración del Repositorio/Build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_STONE_0192A050F }}
          action: "close"
